"""empty message

Revision ID: 503fa2c2e5c7
Revises: 2ce52c2dfd6f
Create Date: 2020-12-04 14:37:41.483352

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '503fa2c2e5c7'
down_revision = '2ce52c2dfd6f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=150), nullable=False),
    sa.Column('password', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
